admin:
  notifications:
    read: true
    create: true
    edit: true
    delete: true

  items:
    read: true
    create: true
    edit: true
    delete: true

  payments:
    read: true
    create: true
    edit: true
    delete: false

manager:
  notifications:
    read: true
    create: false
    edit: false
    delete: false

  items:
    read: true
    create: true
    edit: true
    delete: true

  payments:
    read: true
    create: true
    edit: false
    delete: false

client:
  notifications:
    read: true
    create: false
    edit: false
    delete: false

  items:
    read: true
    create: false
    edit: false
    delete: false

  payments:
    read: true
    create: false
    edit: false
    delete: false
